### ISSUE TITLE
Not inflating XML

### ISSUE THREAD

**Issue by markuspaschke** [manolovn/trianglify#4]
Tried to add this to my project, but its showing me this error, once i start my app:

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/manolovn/colorbrewer/ColorBrewer;
at com.manolovn.trianglify.generator.color.BrewerColorGenerator.<init>(BrewerColorGenerator.java:17)
at com.manolovn.trianglify.renderer.TriangleRenderer.initPaint(TriangleRenderer.java:39)
at com.manolovn.trianglify.renderer.TriangleRenderer.<init>(TriangleRenderer.java:24)
at com.manolovn.trianglify.TrianglifyView.init(TrianglifyView.java:65)
at com.manolovn.trianglify.TrianglifyView.<init>(TrianglifyView.java:50)
 ...
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.manolovn.colorbrewer.ColorBrewer" on path: DexPathList[[zip file "/data/app/com.example.markus.blowout10-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
...
com.manolovn.trianglify.generator.color.BrewerColorGenerator.<init>(BrewerColorGenerator.java:17) 
at com.manolovn.trianglify.renderer.TriangleRenderer.initPaint(TriangleRenderer.java:39) 
at com.manolovn.trianglify.renderer.TriangleRenderer.<init>(TriangleRenderer.java:24) 
at com.manolovn.trianglify.TrianglifyView.init(TrianglifyView.java:65) 
at com.manolovn.trianglify.TrianglifyView.<init>(TrianglifyView.java:50) 
...
Suppressed: java.lang.ClassNotFoundException: com.manolovn.colorbrewer.ColorBrewer
at java.lang.Class.classForName(Native Method)

... 30 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Do you have any advice, maybe incompatible support libraries ?

**Comment by manolovn** [comment]
Sorry, that component depends on https://github.com/manolovn/colorbrewer
Just add it to your project dependencies:
compile 'com.manolovn:colorbrewer:1.0.0'
Renderers abstraction is planned for the next release to break this coupling
